### GET
GET http://localhost:5000/
### GET
GET http://localhost:5000/usuario
### POST
POST http://localhost:5000/usuario
Content-Type: application/json

{
    "firstname": "greg1",
    "lastname": "gregorio honorato",
    "username": "gregorio",
    "password": "gregorio honorato",
    "phone": "19999250999"
}

###

Content-Type: application/json

{
    "external_id": "25"
}
###
GET http://localhost:5000/profissao


###
POST http://localhost:5000/profissao
Content-Type: application/json

{
    "name": "gregorio",
    "cbo_code": "seila",
    "subgroup_code": "nao sei também",
    "requires_description": "aquisição para mim mesmo"
}


###
GET http://localhost:5000/material


###
POST http://localhost:5000/material
Content-Type: application/json

{
    "nome": "borracha de mao",
    "qtde": 11,
    "cor": "amarelo",
    "tamanho": 12
}


###
DELETE http://localhost:5000/material/61b34d4f658d81908dd94aa7
If-Match: 2b451cb7203d874011c5cb93c0243f2243f89ac1


###
PATCH http://localhost:5000/material/61b34d50658d81908dd94aa8
If-Match: 5e74a65240fa080d8d516675bbf163f38124c056
Content-Type: application/json

{
    "cor": "verde"
}

###
GET http://localhost:5000/material/61b34d50658d81908dd94aa8

###
GET http://localhost:5000/jogo


###
POST http://localhost:5000/jogo
Content-Type: application/json

{
    "game_id": "123",
    "titulo": "mario",
    "nome": "mario word"
}
### NAO FUNCIONA ASSIM
GET http://localhost:5000/imagem


###
POST http://localhost:5000/jogo/61b3555e09e9af45bb2cf037/imagem
Content-Type: application/json

{
    "caminho": "tanto faz"
}

###
GET http://localhost:5000/jogo/61b3555e09e9af45bb2cf037/imagem/61b35879e0739b2af008f18d


###
###
POST http://localhost:5000/jogo/61b35a64e0739b2af008f18e/imagem
Content-Type: application/json

{
    "caminho": "outra coisa"
}

###
###
GET http://localhost:5000/jogo/61b35a64e0739b2af008f18e/imagem
###
GET http://localhost:5000/cliente
###
GET http://localhost:5000/cliente/61b23ca00adca480359d62b3
###
POST http://localhost:5000/cliente
### NAO FUNCIONA DIRETAMENTE
GET http://localhost:5000/pessoa


###
POST http://localhost:5000/cliente/61b35ec2e9fd8125df274a1e/pessoa
Content-Type: application/json

{
    "cor": "preto",
    "idade": 18
}